import streamlit as st
from engine import run_growth_engine
import time
import uuid
import json
from datetime import datetime
import os

# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(
    page_title="DataVex Growth Engine",
    page_icon="",
    layout="wide"
)

# Custom CSS for a professional look
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #007bff; color: white; }
    .stTextArea>div>div>textarea { font-family: 'Inter', sans-serif; }
    </style>
    """, unsafe_allow_html=True)

st.title("DataVex Growth Intelligence Engine")
st.markdown("### Autonomous Signal → Strategy → Content System")

st.divider()

# Initialize session storage
if "result" not in st.session_state:
    st.session_state.result = None

# ===============================
# INPUT SECTION
# ===============================
with st.sidebar:
    st.header("⚙️ Control Panel")
    keyword = st.text_input("🔎 Enter Research Keyword", placeholder="e.g. PropTech AI trends")
    run_btn = st.button("🚀 Run AI Growth Engine")
    st.info("Member 1: Coder | Member 2: Strategy | Member 3: Design")

if run_btn:
    if keyword.strip() == "":
        st.warning("⚠️ Please enter a keyword.")
    else:
        with st.spinner("🤖 Agents are coordinating (Cerebras Inference)..."):
            # This calls the updated engine with 6 agents
            st.session_state.result = run_growth_engine(keyword)

# ===============================
# DISPLAY RESULT (Agentic Trace)
# ===============================
if st.session_state.result:
    res = st.session_state.result

    # 1. THE SIGNAL & BRAIN (The Foundation)
    st.header("Step 1: Intelligence Analysis")
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("scout Agent (Raw Signal)")
        st.info(res.get("signal", "No signal found."))

    with col2:
        st.subheader("Brain Agent (Relevance)")
        if "APPROVED" in res.get("brain", "").upper():
            st.success(res.get("brain"))
        else:
            st.error(res.get("brain"))
            st.stop() # Stop if rejected

    # 2. THE STRATEGY (Requirement #3)
    st.divider()
    st.header("Step 2: Growth Strategy")
    with st.expander("View DataVex Strategy Brief", expanded=True):
        st.write(res.get("strategy", "Strategy brief not generated."))

    # 3. THE CRITIQUE LOOP (The Trace)
    st.divider()
    st.header(" Step 3: Agentic Critique Trace")
    st.caption("This shows the Writer's first draft and the Critic's brand-alignment feedback.")
    
    trace_col1, trace_col2 = st.columns(2)
    with trace_col1:
        st.markdown("**Writer's First Draft (V1)**")
        st.text_area("v1_box", res.get("first_draft", ""), height=200, disabled=True, label_visibility="collapsed")
    
    with trace_col2:
        st.markdown("**Critic Feedback (The Trace)**")
        st.warning(res.get("trace", "No critique log found."))

    # 4. FINAL ASSETS (Human-in-the-Loop)
    st.divider()
    st.header("✨ Step 4: Final Publish-Ready Assets")
    
    # Display Generated Image
    if res.get("image") and res["image"].get("url"):
        st.subheader("🖼️ AI-Generated Visual")
        
        st.image(res["image"]["url"], 
                 caption="Generated by DataVex Designer Agent", 
                 width=200)
    
    # Final Content Editor
    st.subheader("📝 Final Copywriting")
    edited_content = st.text_area(
        "Human Review: Edit the final polished content before publishing",
        value=res.get("content", ""),
        height=400,
        key="editor"
    )

    # ===============================
    # APPROVE & PUBLISH
    # ===============================
    if st.button(" Approve & Auto-Publish to DataVex Socials"):
        with st.status("Publishing Workflow...") as status:
            st.write("Authenticating with API...")
            time.sleep(1)
            st.write("Uploading generated image...")
            time.sleep(1)
            st.write("Posting to LinkedIn & X...")
            
            tweet_id = str(uuid.uuid4())[:8]
            tweet_url = f"https://x.com/datavex_ai/status/{tweet_id}"

            post_data = {
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "keyword": keyword,
                "tweet_id": tweet_id,
                "tweet_url": tweet_url,
                "content": edited_content
            }

            # Save to JSON log
            if not os.path.exists("posted_content.json"):
                with open("posted_content.json", "w") as f: json.dump([], f)
            with open("posted_content.json", "r") as f: posts = json.load(f)
            posts.append(post_data)
            with open("posted_content.json", "w") as f: json.dump(posts, f, indent=4)
            
            status.update(label="Published Successfully!", state="complete", expanded=False)

        st.success(f"🔗 View Live Post: {tweet_url}")
        st.balloons()

# ===============================
# POST HISTORY LOG
# ===============================
st.divider()
st.header("📜 Published Content Log")
if os.path.exists("posted_content.json"):
    with open("posted_content.json", "r") as f:
        posts = json.load(f)
    if posts:
        for post in reversed(posts):
            with st.expander(f"🕒 {post['timestamp']} - Keyword: {post['keyword']}"):
                st.write(f"**URL:** {post['tweet_url']}")
                st.write(post["content"])
    else:
        st.info("No published posts yet.")